//发送群聊机器人消息
export const EVENT_SEND_ROBOT_MESSAGE = "EVENT_SEND_ROBOT_MESSAGE";

//批量导出店铺数据
export const EVENT_START_EXPORT_STORE_DATA = "EVENT_START_EXPORT_STORE_DATA";

//批量导出Top榜数据
export const EVENT_START_EXPORT_TOP_DATA = "EVENT_START_EXPORT_TOP_DATA";

//自定义搜索导出数据
export const EVENT_START_EXPORT_SEARCH_DATA = "EVENT_START_EXPORT_SEARCH_DATA";

//自定义搜索导出数据
export const EVENT_START_GET_DETAIL_DATA = "EVENT_START_GET_DETAIL_DATA";

//自定义搜索导出数据
export const SEND_STORE_PRODUCT_LIST = "SEND_STORE_PRODUCT_LIST";

//获取到商品链接
export const SEND_STORE_PRODUCT_LINK = "SEND_STORE_PRODUCT_LINK";